def set_image(x: int):
        # 1 -> Loading GIF, 2 -> Greeting, 3 -> Listening, 4 -> Speaking 1, 5 -> Speaking 2
        match x:
            case 1: 
                ...
            case 2:
                ...
            case 3:
                ...
            case 4:
                ...
            case 5:
                ...